team_one = ['JMORIN', 'AWESTWOO', 'DCHARTRA', 'GLAURIN', 'GPAQUIN', 'GVALLEE', 'JGRENON',
            'JLABERGE', 'KFEKKAR', 'MCOUTURE', 'MOUELLET', 'MPOIRIER', 'MROUTHIE', 'NKJONES',
            'PSIMARD', 'SFRICOTT']
team_snake = ['CGAGNON', 'EBROOKER', 'FLANGLOI', 'JRICHARD', 'LDOBSON', 'NTHIVIER', 'RLEROUX',
              'SDERY', 'SROY', 'SSTPIERR', 'XWANG', 'ZDEJANOV']
team_calvin = 'CBOYCE'
